name: data
description: a data visualization results for JCF government project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_charts: ^24.1.47+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  cupertino_icons: ^1.0.2
  syncfusion_flutter_xlsio: ^24.1.47
  path_provider: ^2.1.0
  open_file: ^3.3.2
  io: ^1.0.4
  http: ^0.13.5
  faker: ^2.1.0
  json_table: ^2.0.1
  rxdart: ^0.27.7
  dropdownfield: ^1.0.3
  google_fonts: ^4.0.4
  fl_chart: ^0.62.0
  flutter_svg: ^1.1.6
  provider: ^6.1.1
  adaptive_theme: ^3.2.1
  percent_indicator: ^4.2.3
  data_table_2: ^2.3.11
  scrollable_positioned_list: ^0.3.8
  animated_splash: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/porGeneroAnioPresupuestal.json
    - assets/images/
    - assets/images/logo.png

  fonts:
    - family: 's'
      fonts:
        - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #         weight: 700
